services:
  app:
    image: simple-video-downloader:development
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - 3000:3000
    networks:
      - sardis_network
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/sardis
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - SECRET_CODE=${SECRET_CODE}
    volumes:
      - ./:/rails
    depends_on:
      - db
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
  worker:
    image: simple-video-downloader:development
    build:
      context: .
      dockerfile: Dockerfile.development
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/sardis
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - SECRET_CODE=${SECRET_CODE}
    volumes:
      - ./:/rails
    depends_on:
      - db
    networks:
      - sardis_network
    command: ["bin/rails", "jobs:work", "-q", "default"]
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=sardis
    ports:
      - 5432:5432
    networks:
      - sardis_network
    volumes:
      - sardis_postgres_data:/var/lib/postgresql/data

volumes:
  sardis_postgres_data:
networks:
  sardis_network:
